plugins {
    id 'java-library' // api 구성을 사용하기 위해 플러그인 추가 필요
}

dependencies {
    // 수정된 부분: :backend: 를 추가합니다.
    implementation project(':module-core')
    implementation project(':module-common')

    // ✅ JWT 추가
    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
}